### ISSUE TITLE
Yum Download errors ignored

### ISSUE THREAD

**Issue by iav** [alanfranz/docker-rpm-builder-configurations#1]
My network requires http proxy with auth to access to internet.
Just installed into fresh Centos 7, http_proxy set into env and docher config, docker-rpm-builder selftest finished with ok.
run 
docker-rpm-builder selftest --full
See somebody somewhere can't fetch packages, but ignores error and still try to buid something:

```
test_docker_scripts_permissions (integration_test_basic.TestBasicIntegration) ... ok
test_created_binaries_have_proper_ownership (integration_test_dir_command.TestDirCommand) ... 2016-03-03T17:51:37+0200 INFO [drb.commands.dir] Now downloading sources
2016-03-03T17:51:37+0200 INFO [drb.downloadsources] Downloading additional sources
2016-03-03T17:51:45+0200 INFO [drb.commands.dir] Now building project from /tmp/drb-temp.T7SR7C on image alanfranz/drb-epel-7-x86-64:latest
2016-03-03T18:35:05+0200 ERROR [UserExceptionTransformer] Full catched exception:
Traceback (most recent call last):
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/commands/dir.py", line 148, in dir
    docker.do_run()
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/docker.py", line 75, in do_run
    return self._run().strip()
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/docker.py", line 95, in _run
    raise SpawnedProcessError(retcode, fullcmd, output=output, error=error)
SpawnedProcessError: Command '/usr/bin/docker run --tty --rm --volume=/tmp/drb-temp.T7SR7C/tmux.spec:/root/rpmbuild/SPECS/tmux.spec:ro --volume=/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/dockerscripts:/dockerscripts:ro --volume=/tmp/drb-temp.T7SR7C:/root/rpmbuild/SOURCES:ro --volume=/tmp/drb-temp.6HnlwD:/root/rpmbuild/RPMS --workdir=/dockerscripts --env=CALLING_UID=0 --env=CALLING_GID=1234 --env=BASH_ON_FAIL='' alanfranz/drb-epel-7-x86-64:latest ./rpmbuild-dir-in-docker.sh' returned non-zero exit status 1:
+ '[' -z 0 ']'
+ '[' -z 1234 ']'
+ '[' -z '' ']'
+ echo 'Missing BASH_ON_FAIL. Won'\''t drop into interactive shell if errors are found'
Missing BASH_ON_FAIL. Won't drop into interactive shell if errors are found
++ rpm --eval '%{_rpmdir}'
+ RPMS_DIR=/root/rpmbuild/RPMS
++ rpm --eval '%{_srcrpmdir}'
+ SRPMS_DIR=/root/rpmbuild/SRPMS
++ rpm --eval '%{_sourcedir}'
+ SOURCE_DIR=/root/rpmbuild/SOURCES
++ rpm --eval '%{_specdir}'
+ SPECS_DIR=/root/rpmbuild/SPECS
++ rpm --eval '%{_arch}'
+ ARCH=x86_64
+ trap finish EXIT
+ echo 'starting ./rpmbuild-dir-in-docker.sh'
starting ./rpmbuild-dir-in-docker.sh
++ ls /root/rpmbuild/SPECS/tmux.spec
++ head -n 1
+ SPEC=/root/rpmbuild/SPECS/tmux.spec
+ /dockerscripts/rpm-setup-deps.sh
+ echo 'starting /dockerscripts/rpm-setup-deps.sh'
starting /dockerscripts/rpm-setup-deps.sh
++ rpm --eval '%{_specdir}'
+ SPECS_DIR=/root/rpmbuild/SPECS
++ head -n 1
++ ls /root/rpmbuild/SPECS/tmux.spec
+ SPEC=/root/rpmbuild/SPECS/tmux.spec
+ yum-builddep -y --nogpgcheck /root/rpmbuild/SPECS/tmux.spec
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os error was
14: curl#7 - "Failed to connect to 2a01:c0:2:4:0:acff:fe1e:1e52: Network is unreachable"
http://pubmirrors.dal.corespace.com/centos/7.2.1511/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://pubmirrors.dal.corespace.com/centos/7.2.1511/os/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Trying other mirror.
http://mirror.ash.fastserv.com/pub/linux/centos/7.2.1511/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.ash.fastserv.com/pub/linux/centos/7.2.1511/os/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30000 milliseconds')
Trying other mirror.
```

How to  provide proxy settings inside?
Why it build something after error with making build envirounment?

**Comment by alanfranz** [comment]
Hello,
I don't understand your logs. Did you copy/paste twice the same log? The timestamp seems to be repeating. If you didn't, maybe it's a logging issue causing the printout twice, I should checkout that. As far as I can understand the build exits after yum-builddep fails.

Probably running the full test suite in your scenario is a bit complex. But since docker doesn't solve that in a global way, requiring that you solve it per-image, I think I won't fix that.

About your other question - how to let the proxy work inside the docker-rpm-builder -, it's really docker-related. Containers don't inherit the host's environment (would a virtual machine do?); so you could choose between:
1) create a new Dockerfile inheriting from my example configurations, and use ENV directives https://docs.docker.com/engine/reference/builder/#env to set http_proxy and https_proxy; build that image (either on Docker hub, or locally, as you prefer) and use it.
2) whenever you build, add an option to be forwarded to docker (at the end of the docker-rpm-builder command line, add two dashes, then everything else is forwarded to the docker command line client), just like the dns in the examples in my docs, e.g.

`docker-rpm-builder dir a682b68bbaba . /tmp/rpms -- --env=http_proxy=http://something:1234`

you can pass multiple --env switches with different variables.

**Comment by iav** [comment]
1. Yes, possible there just sudden twice paste. I am sorry for that.
2. I am very fresh and soft docker user - it's very hard for me to recreate images for a while. Then  I try to cheese a shorten way - --env

seems only one var can be set this way
note `docker: Error parsing reference: "http_proxy=http://xxx:xxx@proxy.local:8080" is not a valid repository/tag.`
:

```
[iav@build7 ~]$ docker-rpm-builder srcrpm --verbose alanfranz/drb-epel-5-x86-64:latest zabbix-2.4.7-2.fc24.src.rpm /tmp/rpms -- --env https_proxy=http://xxx:xxx@proxy.local:8080 --env http_proxy=http://xxx:xxx@proxy.local:8080
2016-03-03T22:54:08+0200 DEBUG [Docker] Now executing:
/bin/docker run --tty --rm alanfranz/drb-epel-5-x86-64:latest rpm --eval '%{_srcrpmdir}'

2016-03-03T22:54:10+0200 DEBUG [Docker] Now executing:
/bin/docker run --tty --rm alanfranz/drb-epel-5-x86-64:latest rpm --eval '%{_rpmdir}'

2016-03-03T22:54:13+0200 INFO [drb.commands.srcrpm] Now building /home/iav/zabbix-2.4.7-2.fc24.src.rpm on image alanfranz/drb-epel-5-x86-64:latest
2016-03-03T22:54:13+0200 DEBUG [Docker] Now executing:
/bin/docker run --tty --rm --env https_proxy=http://xxx:xxx@proxy.local:8080 http_proxy=http://xxx:xxx@proxy.local:8080 --volume=/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/dockerscripts:/dockerscripts:ro --volume=/tmp/drb-temp.aRr_hM:/usr/src/redhat/SRPMS:ro --volume=/tmp/rpms:/usr/src/redhat/RPMS --workdir=/dockerscripts --env=CALLING_UID=1000 --env=CALLING_GID=1000 --env=BASH_ON_FAIL='' --env=RPMBUILD_OPTIONS=--nosignature --env=SRCRPM=zabbix-2.4.7-2.fc24.src.rpm alanfranz/drb-epel-5-x86-64:latest ./rpmbuild-srcrpm-in-docker.sh

docker: Error parsing reference: "http_proxy=http://xxx:xxx@proxy.local:8080" is not a valid repository/tag.
See '/bin/docker run --help'.
2016-03-03T22:54:13+0200 ERROR [UserExceptionTransformer] Full catched exception:
Traceback (most recent call last):
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/commands/srcrpm.py", line 124, in srcrpm
    docker.do_launch_interactively()
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/docker.py", line 71, in do_launch_interactively
    self._run(fds={"stdout":1, "stderr":2, "stdin":0})
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/docker.py", line 95, in _run
    raise SpawnedProcessError(retcode, fullcmd, output=output, error=error)
SpawnedProcessError: Command '/bin/docker run --tty --rm --env https_proxy=http://xxx:xxx@proxy.local:8080 http_proxy=http://xxx:xxx@proxy.local:8080 --volume=/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/dockerscripts:/dockerscripts:ro --volume=/tmp/drb-temp.aRr_hM:/usr/src/redhat/SRPMS:ro --volume=/tmp/rpms:/usr/src/redhat/RPMS --workdir=/dockerscripts --env=CALLING_UID=1000 --env=CALLING_GID=1000 --env=BASH_ON_FAIL='' --env=RPMBUILD_OPTIONS=--nosignature --env=SRCRPM=zabbix-2.4.7-2.fc24.src.rpm alanfranz/drb-epel-5-x86-64:latest ./rpmbuild-srcrpm-in-docker.sh' returned non-zero exit status 125:
None
None

Error: docker run error
Command '/bin/docker run --tty --rm --env https_proxy=http://xxx:xxx@proxy.local:8080 http_proxy=http://xxx:xxx@proxy.local:8080 --volume=/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/dockerscripts:/dockerscripts:ro --volume=/tmp/drb-temp.aRr_hM:/usr/src/redhat/SRPMS:ro --volume=/tmp/rpms:/usr/src/redhat/RPMS --workdir=/dockerscripts --env=CALLING_UID=1000 --env=CALLING_GID=1000 --env=BASH_ON_FAIL='' --env=RPMBUILD_OPTIONS=--nosignature --env=SRCRPM=zabbix-2.4.7-2.fc24.src.rpm alanfranz/drb-epel-5-x86-64:latest ./rpmbuild-srcrpm-in-docker.sh' returned non-zero exit status 125:
None
None
```

**Comment by alanfranz** [comment]
OK that you're fresh, but you should be able to read either my responses or
'docker run --help' :-)

the syntax is '--env=http_proxy=http://proxy:8080'. You forgot one = .

**Comment by aframachines** [comment]
One additional, important detail: you're using EPEL5 as a target. Please be
aware that the original yum-builddep from such distro version is very
limited, and I had to create an "hacked" version of a more functional one,
but some functionality may not be perfect.

**Comment by iav** [comment]
Ok, I have success build of stunnel package. It's good start point for investigations.
Thank you for help - and good tool!
